namespace:
  name: static

deployment:
  name: boxes
  image: __IMAGE_NAME__:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: boxes
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

ingress:
  name: boxes
  hosts:
    - name: boxes.carstens.tech
  secret: tls-boxes
  issuer: letsencrypt-issuer

service:
  name: boxes
  port: 8080
  targetPort: 8080
  appSelector: boxes
